environment:

  matrix:
    - PYTHON: "C:\\Python27"

install:

  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install -r requirements.txt
  - easy_install scons
  - python bin/downloads.py

before_test:

  - python --version
  - scons --version

build: off

test_script:
  - scons test
  - scons unit-test
