#
# Copyright (c) 2017 by Pawel Tomulik
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE

import SCons.Util
import os.path

Import('env')

env.SetDefault(DOCBOOK_PREFER_XSLTPROC = True)
env.Tool('docbook')
overrides = { 'DOCBOOK_XSLTPROCFLAGS' : [SCons.Util.CLVar('--xinclude')] }

html_xsl = env.arg2nodes('html.xsl')
manual_html = env.DocbookHtml('manual.html', 'manual.xml', xsl = html_xsl, **overrides)
css_src = env.File('scons-arguments-${PACKAGE}.css').srcnode(),
css = env.Command('scons-arguments-${PACKAGE}.css', css_src, Copy("$TARGET","$SOURCE"))
env.Depends(manual_html, css)

env.Ignore('..', '.')
env.Clean('..', '.')
env.AlwaysBuild(env.Alias('user-doc', manual_html))
